"use client";
import { useActionState } from "react";
import { LoaderCircle } from "lucide-react";
import { completeChallenge, createCircle, joinCircle, type CommunityState } from "@/actions/community";
import { Button } from "@/components/ui/button";
const empty = {} as CommunityState;
export function CreateCircleForm() { const [state, action, pending] = useActionState(createCircle, empty); return <form action={action} className="grid gap-3"><input required name="name" maxLength={60} className="rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm outline-none focus:border-cyan-300/60" placeholder="e.g. Campus builders" />{state.error && <p role="alert" className="text-xs text-red-200">{state.error}</p>}{state.success && <p role="status" className="text-xs text-cyan-100">{state.success}</p>}<Button disabled={pending} size="sm" type="submit">{pending && <LoaderCircle className="size-3.5 animate-spin" />}Create circle</Button></form>; }
export function JoinCircleForm() { const [state, action, pending] = useActionState(joinCircle, empty); return <form action={action} className="grid gap-3"><input required name="inviteCode" minLength={6} maxLength={12} className="rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 font-mono text-sm uppercase outline-none focus:border-cyan-300/60" placeholder="INVITE CODE" />{state.error && <p role="alert" className="text-xs text-red-200">{state.error}</p>}{state.success && <p role="status" className="text-xs text-cyan-100">{state.success}</p>}<Button disabled={pending} variant="outline" size="sm" type="submit">Join circle</Button></form>; }
export function ChallengeButton({ challengeId, completed }: { challengeId: string; completed: boolean }) { const [state, action, pending] = useActionState(completeChallenge, empty); return <form action={action} className="mt-4"><input type="hidden" name="challengeId" value={challengeId} />{completed ? <p className="text-xs font-semibold text-cyan-100">Completed</p> : <Button disabled={pending} size="sm" type="submit">{pending && <LoaderCircle className="size-3.5 animate-spin" />}Mark challenge done</Button>}{state.error && <p role="alert" className="mt-2 text-xs text-red-200">{state.error}</p>}{state.success && <p role="status" className="mt-2 text-xs text-cyan-100">{state.success}</p>}</form>; }
