"use client";
import { useActionState } from "react";
import { LoaderCircle } from "lucide-react";
import { applyForJob, createJob, updateCareerProfile, type CareerState } from "@/actions/career";
import { Button } from "@/components/ui/button";
const empty = {} as CareerState;
function Notice({ state }: { state: CareerState }) { return <>{state.error && <p role="alert" className="text-sm text-red-200">{state.error}</p>}{state.success && <p role="status" className="text-sm text-cyan-100">{state.success}</p>}</>; }
export function CareerProfileForm({ profile }: { profile: Record<string, string | boolean | null> }) { const [state, action, pending] = useActionState(updateCareerProfile, empty); return <form action={action} className="mt-7 grid gap-4"><label>Name<input name="name" required defaultValue={String(profile.name ?? "")} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 outline-none" /></label><label>Headline<input name="headline" defaultValue={String(profile.headline ?? "")} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 outline-none" /></label><label>Bio<textarea name="bio" defaultValue={String(profile.bio ?? "")} rows={3} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 outline-none" /></label><div className="grid gap-4 sm:grid-cols-2"><label>Location<input name="location" defaultValue={String(profile.location ?? "")} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 outline-none" /></label><label>Website<input name="website" type="url" defaultValue={String(profile.website ?? "")} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 outline-none" /></label></div><label>LinkedIn URL<input name="linkedinUrl" type="url" defaultValue={String(profile.linkedin_url ?? "")} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 outline-none" /></label><label>Resume summary<textarea name="resumeSummary" defaultValue={String(profile.resume_summary ?? "")} rows={5} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 outline-none" /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="portfolioVisible" defaultChecked={Boolean(profile.portfolio_visible)} /> Make my portfolio public</label><Notice state={state} /><Button type="submit" disabled={pending}>{pending && <LoaderCircle className="size-4 animate-spin" />}Save profile</Button></form>; }
export function JobForm() { const [state, action, pending] = useActionState(createJob, empty); return <form action={action} className="grid gap-3"><input name="title" required placeholder="Role title" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 outline-none" /><input name="company" required placeholder="Company" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 outline-none" /><textarea name="description" required minLength={30} rows={5} placeholder="Role description" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 outline-none" /><input name="location" placeholder="Location" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 outline-none" /><input name="applyUrl" type="url" placeholder="External apply URL (optional)" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 outline-none" /><label className="text-sm"><input name="remote" type="checkbox" defaultChecked className="mr-2" />Remote friendly</label><Notice state={state} /><Button disabled={pending} type="submit">Publish job</Button></form>; }
export function ApplyForm({ jobId }: { jobId: string }) { const [state, action, pending] = useActionState(applyForJob, empty); return <form action={action} className="mt-4"><input type="hidden" name="jobId" value={jobId} /><textarea name="note" maxLength={1200} rows={3} placeholder="Short note to the hiring team (optional)" className="w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm outline-none" /><Notice state={state} /><Button disabled={pending} size="sm" type="submit" className="mt-3">{pending && <LoaderCircle className="size-3.5 animate-spin" />}Apply with SpidyCode profile</Button></form>; }
