import { CheckCircle2, Circle, LockKeyhole, Play } from "lucide-react";
import { DashboardShell } from "@/components/dashboard/dashboard-shell";
import { Button } from "@/components/ui/button";
import { startRoadmap } from "@/actions/roadmaps";
import { CompleteLevelButton } from "@/components/roadmaps/complete-level-button";
import { getRoadmap } from "@/features/roadmaps/data-access";

export default async function RoadmapDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const { roadmap, levels, started, completedLevelIds } = await getRoadmap(slug); const completed = levels.filter((level) => completedLevelIds.has(level.id)).length;
  return <DashboardShell><section className="max-w-3xl"><div className="flex items-start gap-4"><span className="grid size-14 place-items-center rounded-2xl bg-violet-300/10 font-mono text-lg text-violet-100">{roadmap.icon}</span><div><p className="font-mono text-xs uppercase text-cyan-200">{roadmap.difficulty}</p><h1 className="mt-1 text-3xl font-bold tracking-[-.05em]">{roadmap.title}</h1><p className="mt-2 max-w-xl text-sm leading-6 text-white/55">{roadmap.description}</p></div></div><div className="mt-8 rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="flex items-center justify-between text-sm"><span className="font-medium">Your progress</span><span className="font-mono text-xs text-cyan-100">{completed} / {levels.length} levels</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div style={{ width: `${levels.length ? completed / levels.length * 100 : 0}%` }} className="h-full rounded-full bg-gradient-to-r from-violet-400 to-cyan-300" /></div></div>{!started ? <form action={startRoadmap.bind(null, roadmap.id, roadmap.slug)} className="mt-7"><Button type="submit"><Play className="size-4" />Start this roadmap</Button></form> : <ol className="mt-8 space-y-4">{levels.map((level, index) => { const isComplete = completedLevelIds.has(level.id); const unlocked = index === 0 || completedLevelIds.has(levels[index - 1]?.id); return <li key={level.id} className={`rounded-2xl border p-5 ${isComplete ? "border-cyan-300/25 bg-cyan-300/[.045]" : "border-white/10 bg-white/[.025]"}`}><div className="flex gap-4"><span className="mt-0.5">{isComplete ? <CheckCircle2 className="size-5 text-cyan-200" /> : unlocked ? <Circle className="size-5 text-violet-200" /> : <LockKeyhole className="size-5 text-white/25" />}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">{String(level.position).padStart(2, "0")} · {level.title}</h2><span className="font-mono text-[10px] text-white/45">+{level.xp_reward} XP</span></div><p className="mt-2 text-sm leading-6 text-white/55">{level.description}</p>{isComplete ? <p className="mt-4 inline-flex items-center gap-2 text-xs font-semibold text-cyan-100"><CheckCircle2 className="size-3.5" />Completed</p> : unlocked ? <CompleteLevelButton levelId={level.id} xp={level.xp_reward} /> : <p className="mt-4 text-xs text-white/35">Finish the previous level to unlock this mission.</p>}</div></div></li>; })}</ol>}</section></DashboardShell>;
}
