import { CheckCircle2, Circle, LockKeyhole, Play } from "lucide-react";
import { DashboardShell } from "@/components/dashboard/dashboard-shell";
import { Button } from "@/components/ui/button";
import { startRoadmap } from "@/actions/roadmaps";
import { CompleteLevelButton } from "@/components/roadmaps/complete-level-button";
import { getRoadmap } from "@/features/roadmaps/data-access";

export default async function RoadmapDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const { roadmap, levels, started, completedLevelIds } = await getRoadmap(slug); const completed = levels.filter((level) => completedLevelIds.has(level.id)).length;
  const progress = levels.length ? Math.round((completed / levels.length) * 100) : 0;
  return <DashboardShell><section className="max-w-3xl"><div className="flex items-start gap-4 sm:gap-5"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-violet-300/10 font-mono text-base text-violet-100 sm:size-14 sm:text-lg">{roadmap.icon}</span><div><p className="page-kicker">{roadmap.difficulty}</p><h1 className="page-title mt-1">{roadmap.title}</h1><p className="page-description mt-2">{roadmap.description}</p></div></div><div className="glass-surface mt-8 rounded-3xl border border-white/10 p-5 sm:p-6"><div className="flex items-center justify-between gap-4 text-sm"><div><p className="font-semibold">Your progress</p><p className="mt-1 text-xs text-white/45">{started ? "Keep moving through each mission." : "Start when you are ready to commit."}</p></div><span className="rounded-full bg-cyan-300/10 px-3 py-1.5 font-mono text-xs text-cyan-100">{progress}%</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/10"><div style={{ width: `${progress}%` }} className="h-full rounded-full bg-gradient-to-r from-violet-400 to-cyan-300 transition-[width] duration-700" /></div><div className="mt-3 flex justify-between font-mono text-[10px] uppercase tracking-wide text-white/40"><span>{completed} complete</span><span>{levels.length} levels</span></div>{!started ? <form action={startRoadmap.bind(null, roadmap.id, roadmap.slug)} className="mt-7"><Button type="submit"><Play className="size-4" />Start this roadmap</Button></form> : <ol className="mt-8 space-y-3">{levels.map((level, index) => { const isComplete = completedLevelIds.has(level.id); const unlocked = index === 0 || completedLevelIds.has(levels[index - 1]?.id); return <li key={level.id} className={`transition duration-300 ${isComplete ? "rounded-2xl border border-cyan-300/25 bg-cyan-300/[.045]" : "rounded-2xl border border-white/10 bg-white/[.025]"}`}><div className="flex gap-4 p-4 sm:p-5"><span className="mt-0.5">{isComplete ? <CheckCircle2 className="size-5 text-cyan-200" /> : unlocked ? <Circle className="size-5 text-violet-200" /> : <LockKeyhole className="size-5 text-white/25" />}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">{String(level.position).padStart(2, "0")} · {level.title}</h2><span className="rounded-full border border-white/10 px-2 py-1 font-mono text-[10px] text-white/45">+{level.xp_reward} XP</span></div><p className="mt-2 text-sm leading-6 text-white/55">{level.description}</p>{isComplete ? <p className="mt-4 inline-flex items-center gap-2 text-xs font-semibold text-cyan-100"><CheckCircle2 className="size-3.5" />Completed</p> : unlocked ? <CompleteLevelButton levelId={level.id} xp={level.xp_reward} /> : <p className="mt-4 text-xs text-white/35">Finish the previous level to unlock this mission.</p>}</div></div></li>; })}</ol>}</div></section></DashboardShell>;
}
