import Link from "next/link";
import { Award } from "lucide-react";
import { DashboardShell } from "@/components/dashboard/dashboard-shell";
import { Button } from "@/components/ui/button";
import { requestCertificate } from "@/actions/career";
import { requireUser } from "@/lib/auth/dal";
import { createAdminClient } from "@/supabase/admin";
// @ts-expect-error Generated relation type is not available in the local client.
export default async function CertificatesPage() { const user = await requireUser(); const admin = createAdminClient(); const [{ data: started }, { data: certificates }] = await Promise.all([admin.from("user_roadmaps").select("roadmaps(id,title)").eq("user_id", user.id), admin.from("certificates").select("id,verification_code,roadmaps(id,title)").eq("user_id", user.id)]); return <DashboardShell><section className="mx-auto max-w-3xl"><p className="font-mono text-xs text-cyan-200">CERTIFICATES</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Make your progress verifiable.</h1><div className="mt-7 grid gap-4">{(started ?? []).map((item) => { const roadmap = item.roadmaps as { id: string; title: string } | null; if (!roadmap) return null; const certificate = (certificates ?? []).find((entry) => (entry.roadmaps as { id: string } | null)?.id === roadmap.id); return <article key={roadmap.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-white/10 bg-white/[.035] p-5"><div><h2 className="font-semibold">{roadmap.title}</h2><p className="mt-1 text-sm text-white/50">Available when every roadmap level is complete.</p></div>{certificate ? <Link href={`/certificates/${certificate.id}`} className="text-sm font-semibold text-cyan-100">View certificate →</Link> : <form action={requestCertificate.bind(null, roadmap.id)}><Button size="sm" type="submit"><Award className="size-3.5" />Request certificate</Button></form>}</article>; })}</div></section></DashboardShell>; }
