import Link from "next/link";
import { AlertTriangle, ArrowUpRight, CheckCircle2, CircleDashed, Github, ShieldCheck, Sparkles } from "lucide-react";
import { DashboardShell } from "@/components/dashboard/dashboard-shell";
import { Button } from "@/components/ui/button";
import { runAiReview } from "@/actions/projects";
import { getProjectForUser } from "@/features/projects/data-access";
type Review = { overall_score: number; code_quality_score: number; performance_score: number; security_score: number; structure_score: number; strengths: string[]; weaknesses: string[]; suggestions: string[]; model: string };
export default async function ProjectPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const { project, review } = await getProjectForUser(id); const result = review as Review | null; return <DashboardShell><section className="mx-auto max-w-4xl"><Link href="/dashboard" className="text-sm font-semibold text-white/55 hover:text-cyan-100">← Dashboard</Link><div className="mt-7 flex flex-col justify-between gap-5 sm:flex-row"><div><p className="font-mono text-xs text-cyan-200">PROJECT REVIEW</p><h1 className="mt-2 text-3xl font-bold tracking-[-.05em]">{project.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/55">{project.description}</p></div><a href={project.github_repo ?? "#"} target="_blank" rel="noreferrer" className="inline-flex h-fit items-center gap-2 rounded-full border border-white/15 bg-white/5 px-4 py-2.5 text-sm font-semibold hover:bg-white/10"><Github className="size-4" />Repository <ArrowUpRight className="size-3.5" /></a></div>{project.review_status === "complete" && result ? <ReviewReport review={result} /> : <div className="mt-8 rounded-3xl border border-white/10 bg-white/[.035] p-7"><div className="flex items-center gap-3"><CircleDashed className="size-5 text-cyan-200" /><div><h2 className="font-semibold">{project.review_status === "failed" ? "Review could not be completed" : "Ready for AI review"}</h2><p className="mt-1 text-sm text-white/55">{project.review_status === "failed" ? "Check that the repository is public and try again." : "Get a structured review from the selected source files in your public repository."}</p></div></div><form action={runAiReview.bind(null, id)} className="mt-6"><Button type="submit"><Sparkles className="size-4" />{project.review_status === "failed" ? "Try review again" : "Run AI review"}</Button></form></div>}</section></DashboardShell>; }
function ReviewReport({ review }: { review: Review }) { const metrics = [["Code quality", review.code_quality_score], ["Performance", review.performance_score], ["Security", review.security_score], ["Structure", review.structure_score]]; return <div className="mt-8 grid gap-5"><div className="rounded-3xl border border-cyan-300/20 bg-cyan-300/[.045] p-7"><div className="flex items-center gap-4"><span className="grid size-16 place-items-center rounded-2xl bg-cyan-300/15 text-2xl font-bold text-cyan-100">{review.overall_score}</span><div><p className="font-mono text-xs text-cyan-200">AI REVIEW SCORE</p><h2 className="mt-1 text-xl font-semibold">Evidence-based code feedback</h2><p className="mt-1 text-xs text-white/45">Generated with {review.model}</p></div></div><div className="mt-7 grid gap-3 sm:grid-cols-4">{metrics.map(([label, score]) => <div key={String(label)}><div className="flex justify-between text-xs"><span className="text-white/60">{label}</span><span className="font-mono text-cyan-100">{score}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/10"><div style={{ width: `${score}%` }} className="h-full rounded-full bg-cyan-300" /></div></div>)}</div></div><div className="grid gap-5 md:grid-cols-2"><Feedback title="Strengths" icon={<CheckCircle2 className="size-4 text-cyan-200" />} entries={review.strengths} /><Feedback title="Watch outs" icon={<AlertTriangle className="size-4 text-amber-200" />} entries={review.weaknesses} /></div><Feedback title="Suggested next steps" icon={<ShieldCheck className="size-4 text-violet-200" />} entries={review.suggestions} /></div>; }
function Feedback({ title, icon, entries }: { title: string; icon: React.ReactNode; entries: string[] }) { return <article className="rounded-2xl border border-white/10 bg-white/[.035] p-6"><h3 className="flex items-center gap-2 text-sm font-semibold">{icon}{title}</h3><ul className="mt-4 grid gap-3 text-sm leading-6 text-white/60">{entries.map((entry) => <li key={entry}>• {entry}</li>)}</ul></article>; }
