"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { getCurrentProfile, requireUser } from "@/lib/auth/dal";
import { createAdminClient } from "@/supabase/admin";
import { createClient } from "@/supabase/server";
export type CareerState = { error?: string; success?: string };
const profileSchema = z.object({ name: z.string().trim().min(2).max(100), headline: z.string().trim().max(140).optional(), location: z.string().trim().max(100).optional(), bio: z.string().trim().max(280).optional(), website: z.union([z.literal(""), z.string().url()]), linkedinUrl: z.union([z.literal(""), z.string().url()]), resumeSummary: z.string().trim().max(1200).optional(), portfolioVisible: z.enum(["on", "off"]).optional() });
export async function updateCareerProfile(_: CareerState, formData: FormData): Promise<CareerState> { const parsed = profileSchema.safeParse({ name: formData.get("name"), headline: formData.get("headline"), location: formData.get("location"), bio: formData.get("bio"), website: formData.get("website"), linkedinUrl: formData.get("linkedinUrl"), resumeSummary: formData.get("resumeSummary"), portfolioVisible: formData.get("portfolioVisible") ?? "off" }); if (!parsed.success) return { error: "Please check the information you entered." }; const user = await requireUser(); const admin = createAdminClient(); const { error } = await admin.from("profiles").update({ name: parsed.data.name, headline: parsed.data.headline || null, location: parsed.data.location || null, bio: parsed.data.bio || null, website: parsed.data.website || null, linkedin_url: parsed.data.linkedinUrl || null, resume_summary: parsed.data.resumeSummary || null, portfolio_visible: parsed.data.portfolioVisible === "on" }).eq("id", user.id); if (error) return { error: "Unable to update your profile." }; revalidatePath("/profile"); revalidatePath(`/u/${(await getCurrentProfile())?.username}`); return { success: "Profile updated." }; }
export async function requestCertificate(roadmapId: string) { const id = z.string().uuid().safeParse(roadmapId); if (!id.success) redirect("/roadmaps"); await requireUser(); const supabase = await createClient(); const { data, error } = await supabase.rpc("issue_certificate", { target_roadmap_id: id.data }); if (error || !data) redirect("/roadmaps"); redirect(`/certificates/${data}`); }
const jobSchema = z.object({ title: z.string().trim().min(3).max(160), company: z.string().trim().min(2).max(120), description: z.string().trim().min(30).max(8000), location: z.string().trim().max(100).optional(), applyUrl: z.union([z.literal(""), z.string().url()]), remote: z.enum(["on", "off"]).optional() });
export async function createJob(_: CareerState, formData: FormData): Promise<CareerState> { const parsed = jobSchema.safeParse({ title: formData.get("title"), company: formData.get("company"), description: formData.get("description"), location: formData.get("location"), applyUrl: formData.get("applyUrl"), remote: formData.get("remote") ?? "off" }); if (!parsed.success) return { error: "Please complete every job field correctly." }; const user = await requireUser(); const profile = await getCurrentProfile(); if (profile?.role !== "recruiter" && profile?.role !== "admin") return { error: "Recruiter access is required." }; const admin = createAdminClient(); const { error } = await admin.from("jobs").insert({ owner_id: user.id, title: parsed.data.title, company: parsed.data.company, description: parsed.data.description, location: parsed.data.location || null, apply_url: parsed.data.applyUrl || null, remote: parsed.data.remote === "on", is_published: true }); if (error) return { error: "Unable to publish this job." }; revalidatePath("/jobs"); return { success: "Job published." }; }
export async function applyForJob(_: CareerState, formData: FormData): Promise<CareerState> { const jobId = z.string().uuid().safeParse(formData.get("jobId")); const note = z.string().trim().max(1200).safeParse(formData.get("note") ?? ""); if (!jobId.success || !note.success) return { error: "Invalid application." }; const user = await requireUser(); const admin = createAdminClient(); const { error } = await admin.from("job_applications").upsert({ job_id: jobId.data, user_id: user.id, note: note.data }, { onConflict: "job_id,user_id", ignoreDuplicates: true }); if (error) return { error: "Unable to submit application." }; return { success: "Application submitted." }; }
