"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireUser } from "@/lib/auth/dal";
import { createAdminClient } from "@/supabase/admin";
import { createClient } from "@/supabase/server";
export type CommunityState = { error?: string; success?: string };
const circleName = z.string().trim().min(3, "Circle name must have at least 3 characters.").max(60);
const inviteCode = z.string().trim().toUpperCase().regex(/^[A-Z0-9]{6,12}$/, "Enter a valid invite code.");
export async function createCircle(_: CommunityState, formData: FormData): Promise<CommunityState> { const name = circleName.safeParse(formData.get("name")); if (!name.success) return { error: name.error.issues[0]?.message }; const user = await requireUser(); const admin = createAdminClient(); const code = crypto.randomUUID().replace(/-/g, "").slice(0, 8).toUpperCase(); const { data: circle, error } = await admin.from("circles").insert({ name: name.data, owner_id: user.id, invite_code: code }).select("id").single(); if (error || !circle) return { error: "Unable to create your circle. Please try again." }; await admin.from("circle_members").insert({ circle_id: circle.id, user_id: user.id, role: "owner" }); revalidatePath("/community"); return { success: `Circle created. Invite code: ${code}` }; }
export async function joinCircle(_: CommunityState, formData: FormData): Promise<CommunityState> { const code = inviteCode.safeParse(formData.get("inviteCode")); if (!code.success) return { error: code.error.issues[0]?.message }; const user = await requireUser(); const admin = createAdminClient(); const { data: circle } = await admin.from("circles").select("id").eq("invite_code", code.data).maybeSingle(); if (!circle) return { error: "We couldn’t find that circle." }; const { error } = await admin.from("circle_members").upsert({ circle_id: circle.id, user_id: user.id }, { onConflict: "circle_id,user_id", ignoreDuplicates: true }); if (error) return { error: "Unable to join this circle." }; revalidatePath("/community"); return { success: "You joined the circle." }; }
export async function completeChallenge(_: CommunityState, formData: FormData): Promise<CommunityState> { const challengeId = z.string().uuid().safeParse(formData.get("challengeId")); if (!challengeId.success) return { error: "Invalid challenge." }; await requireUser(); const supabase = await createClient(); const { data, error } = await supabase.rpc("complete_challenge", { target_challenge_id: challengeId.data }); if (error) return { error: "Unable to complete this challenge." }; const result = data as { alreadyCompleted: boolean; xpEarned?: number }; revalidatePath("/dashboard"); revalidatePath("/community"); return { success: result.alreadyCompleted ? "Challenge already complete." : `Challenge complete — +${result.xpEarned} XP.` }; }
