"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireUser } from "@/lib/auth/dal";
import { githubRepositoryUrl, readPublicRepository } from "@/services/github/repository";
import { reviewProject } from "@/services/ai/review-project";
import { createAdminClient } from "@/supabase/admin";
export type SubmissionState = { error?: string };
const schema = z.object({ levelId: z.string().uuid(), title: z.string().trim().min(3, "Enter a project title.").max(140), description: z.string().trim().min(20, "Describe what you built in at least 20 characters.").max(3000), repositoryUrl: githubRepositoryUrl });
export async function submitProject(_: SubmissionState, formData: FormData): Promise<SubmissionState> { const parsed = schema.safeParse({ levelId: formData.get("levelId"), title: formData.get("title"), description: formData.get("description"), repositoryUrl: formData.get("repositoryUrl") }); if (!parsed.success) return { error: parsed.error.issues[0]?.message }; const user = await requireUser(); const admin = createAdminClient(); const { data: level } = await admin.from("levels").select("id,roadmap_id").eq("id", parsed.data.levelId).maybeSingle(); if (!level) return { error: "That level no longer exists." }; const { data: enrollment } = await admin.from("user_roadmaps").select("user_id").eq("user_id", user.id).eq("roadmap_id", level.roadmap_id).maybeSingle(); if (!enrollment) return { error: "Start this roadmap before submitting a project." }; const { data: project, error } = await admin.from("projects").insert({ user_id: user.id, level_id: parsed.data.levelId, title: parsed.data.title, description: parsed.data.description, github_repo: parsed.data.repositoryUrl.url, status: "submitted", review_status: "queued", submitted_at: new Date().toISOString() }).select("id").single(); if (error || !project) return { error: "We couldn’t save this project. Try again." }; redirect(`/projects/${project.id}`); }
export async function runAiReview(projectId: string) { const parsedId = z.string().uuid().safeParse(projectId); if (!parsedId.success) redirect("/dashboard"); const user = await requireUser(); const admin = createAdminClient(); const { data: project } = await admin.from("projects").select("id,user_id,title,description,github_repo").eq("id", parsedId.data).maybeSingle(); if (!project || project.user_id !== user.id) redirect("/dashboard"); if (!project.github_repo) redirect(`/projects/${parsedId.data}?error=repository`); await admin.from("projects").update({ review_status: "reviewing" }).eq("id", project.id); try { const snapshot = await readPublicRepository(githubRepositoryUrl.parse(project.github_repo)); const { review, model } = await reviewProject({ projectTitle: project.title, projectDescription: project.description, snapshot, safetyIdentifier: user.id }); const { error } = await admin.from("ai_reviews").upsert({ project_id: project.id, model, overall_score: review.overallScore, code_quality_score: review.codeQuality, performance_score: review.performance, security_score: review.security, structure_score: review.structure, strengths: review.strengths, weaknesses: review.weaknesses, suggestions: review.suggestions }, { onConflict: "project_id" }); if (error) throw error; await admin.from("projects").update({ ai_score: review.overallScore, review_status: "complete", status: review.overallScore >= 60 ? "approved" : "needs_changes", completed_at: review.overallScore >= 60 ? new Date().toISOString() : null }).eq("id", project.id); } catch { await admin.from("projects").update({ review_status: "failed" }).eq("id", project.id); } revalidatePath(`/projects/${project.id}`); revalidatePath("/dashboard"); redirect(`/projects/${project.id}`); }
