import Link from "next/link";
import { ArrowRight, BookOpen } from "lucide-react";
import { DashboardShell } from "@/components/dashboard/dashboard-shell";
import { getPublishedRoadmaps } from "@/features/roadmaps/data-access";

export const revalidate = 3600;
export const dynamic = "force-dynamic";

export default async function RoadmapsPage() { const roadmaps = await getPublishedRoadmaps(); return <DashboardShell><section><p className="page-kicker">LEARNING PATHS</p><h1 className="page-title">Pick a direction. Build proof.</h1><p className="page-description">Every roadmap takes you from fundamentals to a real project worth showing.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{roadmaps.map((roadmap, index) => <Link key={roadmap.id} href={`/roadmaps/${roadmap.slug}`} className="motion-reveal surface-link group rounded-2xl border border-white/10 bg-white/[.035] p-5 sm:p-6" style={{ animationDelay: `${index * 55}ms` }}><div className="relative flex items-start justify-between"><span className="grid size-11 place-items-center rounded-xl bg-violet-300/10 font-mono text-sm text-violet-100 transition duration-300 group-hover:scale-110 group-hover:bg-violet-300/15">{roadmap.icon}</span><span className="rounded-full border border-white/10 px-2.5 py-1 font-mono text-[10px] uppercase text-white/45">{roadmap.difficulty}</span></div><h2 className="relative mt-10 text-lg font-semibold sm:mt-12">{roadmap.title}</h2><p className="relative mt-2 min-h-12 text-sm leading-6 text-white/55">{roadmap.description}</p><span className="relative mt-6 inline-flex items-center gap-2 text-sm font-semibold text-cyan-100">View path <ArrowRight className="size-4 transition group-hover:translate-x-1" /></span></Link>)}</div>{roadmaps.length === 0 && <div className="mt-8 rounded-2xl border border-white/10 bg-white/[.03] p-10 text-center"><BookOpen className="mx-auto size-6 text-white/45" /><p className="mt-3 text-sm text-white/55">Roadmaps are being prepared. Please check back soon.</p></div>}</section></DashboardShell>; }
