"use client";

import { ArrowRight, Check, Code2, Crown, GitCommitHorizontal, ShieldCheck, Trophy, UsersRound, Zap } from "lucide-react";
import { motion, useReducedMotion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { AnimatedGrid } from "./animated-grid";

const features = [{ icon: Code2, title: "Projects, not playlists", text: "Every level ends with a polished project you can deploy, show, and be proud to link." }, { icon: UsersRound, title: "Friendly competition", text: "Build alongside your circle. Celebrate streaks, chase ranks, and keep each other honest." }, { icon: ShieldCheck, title: "Verified progress", text: "Smart reviews and tests reward genuine work, so every point on your profile means something." }];
const roadmaps = ["Python", "JavaScript", "React", "Next.js", "Node.js", "DSA", "SQL", "AI"];

export function LandingPage() {
  const reduceMotion = useReducedMotion();
  const fade = { initial: { opacity: 0, y: reduceMotion ? 0 : 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: .18 }, transition: { duration: .55 } };
  return <div className="min-h-screen overflow-x-clip bg-[#05060c] text-white"><AnimatedGrid /><div className="pointer-events-none fixed inset-0 -z-10 bg-[radial-gradient(circle_at_72%_22%,rgba(94,76,230,.18),transparent_25%),radial-gradient(circle_at_22%_60%,rgba(41,211,196,.08),transparent_24%)]" />
    <header className="mx-auto flex h-20 w-[min(1160px,calc(100%-2rem))] items-center justify-between"><a className="flex items-center gap-2.5 font-bold tracking-tight" href="#top"><span className="grid size-8 place-items-center rounded-[10px] bg-gradient-to-br from-violet-300 via-violet-500 to-cyan-300 shadow-[0_0_28px_rgba(124,108,247,.55)]"><Code2 className="size-4" /></span><span>spidycode</span></a><nav aria-label="Main navigation" className="hidden gap-7 text-sm text-white/65 md:flex"><a href="#features" className="hover:text-white">Why Spidy</a><a href="#roadmaps" className="hover:text-white">Roadmaps</a><a href="#leaderboard" className="hover:text-white">Leaderboard</a></nav><Button asChild size="sm" variant="outline"><a href="#start">Join the beta <ArrowRight className="size-3" /></a></Button></header>
    <main id="top"><section className="mx-auto grid min-h-[650px] w-[min(1160px,calc(100%-2rem))] items-center gap-12 py-16 lg:grid-cols-[1.02fr_.98fr]"><motion.div {...fade}><div className="inline-flex items-center gap-2 rounded-full border border-cyan-300/25 bg-cyan-300/5 px-3 py-1.5 font-mono text-[11px] tracking-[.08em] text-cyan-100"><span className="size-1.5 animate-pulse rounded-full bg-cyan-300" /> BUILT FOR AMBITIOUS BEGINNERS</div><h1 className="mt-6 max-w-[660px] text-5xl font-bold leading-[.98] tracking-[-.07em] sm:text-6xl lg:text-7xl">Stop scrolling.<br />Start <span className="bg-gradient-to-r from-violet-300 via-cyan-200 to-pink-300 bg-clip-text text-transparent">shipping.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-white/60">Build real projects, earn your rank, and create the GitHub profile that opens doors. Learning becomes visible progress.</p><div className="mt-8 flex flex-wrap items-center gap-4"><Button asChild><a href="#start">Start learning <ArrowRight className="size-4" /></a></Button><a className="text-sm font-semibold text-white/75 hover:text-cyan-200" href="#roadmaps">Explore roadmaps ↓</a></div><div className="mt-10 flex items-center gap-3 text-xs text-white/50"><div className="flex -space-x-2">{["S", "P", "A", "K"].map((initial, index) => <span key={initial} className={`grid size-7 place-items-center rounded-full border-2 border-[#090a15] text-[10px] font-bold text-black ${["bg-pink-200", "bg-cyan-200", "bg-violet-200", "bg-amber-200"][index]}`}>{initial}</span>)}</div>Join 2,000+ builders learning in public</div></motion.div><DashboardPreview /></section>
    <section className="border-y border-white/10 py-5"><div className="mx-auto flex w-[min(1160px,calc(100%-2rem))] gap-7 overflow-hidden whitespace-nowrap font-mono text-[11px] text-white/45"><span>POWERING THE NEXT WAVE OF</span>{["BUILDERS", "CREATORS", "ENGINEERS", "FOUNDERS", "PROBLEM-SOLVERS"].map((item) => <b key={item} className="text-white/65">{item}</b>)}</div></section>
    <section id="features" className="mx-auto w-[min(1160px,calc(100%-2rem))] py-24"><SectionHeading kicker="Designed to keep you moving" title="Not another course you never finish." text="SpidyCode turns learning into a visible, social game — built around the work that actually matters." /><div className="grid gap-4 md:grid-cols-3">{features.map(({ icon: Icon, title, text }) => <motion.article {...fade} key={title} className="group rounded-2xl border border-white/10 bg-white/[.035] p-6 transition hover:-translate-y-1 hover:border-violet-300/40 hover:bg-violet-300/[.07]"><div className="grid size-11 place-items-center rounded-xl bg-violet-300/10 text-violet-200"><Icon className="size-5" /></div><h3 className="mt-10 text-base font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-white/55">{text}</p></motion.article>)}</div></section>
    <section id="roadmaps" className="mx-auto w-[min(1160px,calc(100%-2rem))] py-12"><SectionHeading kicker="Choose your direction" title="A roadmap that ends with proof." text="Start where you are. Every path is broken into focused levels and projects that build toward a credible portfolio." /><motion.div {...fade} className="rounded-3xl border border-white/10 bg-[radial-gradient(circle_at_82%_0%,rgba(122,102,241,.18),transparent_30%),rgba(255,255,255,.03)] p-6 sm:p-8"><div className="flex flex-col justify-between gap-7 sm:flex-row sm:items-center"><div><p className="font-mono text-xs text-cyan-200">15+ CAREER PATHS</p><h3 className="mt-2 text-xl font-semibold tracking-tight">Pick a skill. Build a body of work.</h3></div><Button asChild variant="outline"><a href="#start">View all roadmaps <ArrowRight className="size-4" /></a></Button></div><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">{roadmaps.map((roadmap, index) => <div key={roadmap} className="rounded-xl border border-white/10 bg-black/20 p-4"><span className="font-mono text-xs text-violet-200">0{index + 1}</span><p className="mt-4 text-sm font-semibold">{roadmap}</p><p className="mt-1 text-xs text-white/45">Project-based path</p></div>)}</div></motion.div></section>
    <section id="leaderboard" className="mx-auto w-[min(1160px,calc(100%-2rem))] py-24"><SectionHeading kicker="Progress is more fun together" title="Compete with the people who push you." text="Private friend circles give every milestone a little more meaning." /><motion.div {...fade} className="grid overflow-hidden rounded-3xl border border-white/10 bg-white/[.035] md:grid-cols-[.8fr_1.2fr]"><div className="border-b border-white/10 p-7 md:border-b-0 md:border-r"><div className="flex items-center gap-2 text-sm font-semibold"><Trophy className="size-4 text-amber-200" /> Weekly leaderboard</div><p className="mt-2 text-sm leading-6 text-white/55">See who is putting in the work this week.</p><div className="mt-8 space-y-4">{[["Aarav Mehta", "2,430", "AM"], ["You", "1,280", "S"], ["Priya Shah", "1,110", "PS"]].map(([name, score, initials], index) => <div key={name} className="flex items-center gap-3"><span className="w-4 font-mono text-xs text-white/40">0{index + 1}</span><span className="grid size-8 place-items-center rounded-full bg-violet-300/15 text-[10px] font-bold text-violet-100">{initials}</span><span className="flex-1 text-sm font-medium">{name}</span><span className="font-mono text-xs text-cyan-100">{score} XP</span></div>)}</div></div><div className="p-7"><p className="font-mono text-xs text-white/45">YOUR MOMENTUM</p><div className="mt-4 flex h-36 items-end gap-3">{[30, 42, 35, 59, 54, 72, 89].map((height, index) => <div key={index} className="flex flex-1 flex-col justify-end"><div style={{ height: `${height}%` }} className={`rounded-t-md ${index === 6 ? "bg-gradient-to-t from-violet-500 to-cyan-300 shadow-[0_0_18px_rgba(85,230,210,.45)]" : "bg-white/10"}`} /></div>)}</div><div className="mt-3 flex justify-between font-mono text-[10px] text-white/40"><span>MON</span><span>SUN</span></div><div className="mt-7 flex items-center gap-3 rounded-xl border border-cyan-300/15 bg-cyan-300/[.05] p-4"><Zap className="size-5 text-cyan-200" /><div><p className="text-sm font-semibold">12-day learning streak</p><p className="mt-1 text-xs text-white/50">You are 3 days from a new personal best.</p></div></div></div></motion.div></section>
    <section id="start" className="mx-auto w-[min(1160px,calc(100%-2rem))] py-16"><motion.div {...fade} className="rounded-3xl border border-violet-300/35 bg-[radial-gradient(circle_at_50%_0%,rgba(123,104,241,.35),transparent_55%),linear-gradient(135deg,#19163a,#101325)] px-6 py-20 text-center"><p className="font-mono text-xs tracking-[.1em] text-cyan-200">YOUR NEXT COMMIT STARTS HERE</p><h2 className="mx-auto mt-4 max-w-2xl text-4xl font-bold tracking-[-.06em] sm:text-5xl">Build the thing you keep thinking about.</h2><p className="mx-auto mt-5 max-w-lg text-sm leading-6 text-white/65">Pick your roadmap. Invite your people. Make today count.</p><Button className="mt-8" asChild><a href="mailto:hello@spidycode.dev?subject=SpidyCode%20beta%20access">Get early access <ArrowRight className="size-4" /></a></Button></motion.div></section></main>
    <footer className="mx-auto flex w-[min(1160px,calc(100%-2rem))] flex-col gap-2 border-t border-white/10 py-7 text-xs text-white/45 sm:flex-row sm:justify-between"><span>© 2026 SpidyCode</span><span>Learn. Build. Compete. Get Hired.</span></footer></div>;
}

function DashboardPreview() { return <motion.div initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .6, delay: .15 }} className="relative mx-auto w-full max-w-[470px] [perspective:1000px]"><div className="rounded-3xl border border-white/15 bg-[linear-gradient(145deg,rgba(35,35,63,.9),rgba(12,13,28,.85))] p-5 shadow-2xl shadow-black/50 backdrop-blur [transform:rotateY(-5deg)_rotateX(3deg)]"><div className="flex justify-between font-mono text-[10px] text-white/45"><span>SPIDYCODE / DASHBOARD</span><span className="rounded-full bg-cyan-300/10 px-2 py-1 text-cyan-100">● IN PROGRESS</span></div><p className="mt-6 text-xl font-semibold tracking-tight">Good evening, Sid ✦</p><p className="mt-1 font-mono text-xs text-white/45">Your next project is waiting.</p><div className="mt-5 rounded-2xl border border-white/10 bg-white/[.045] p-4"><div className="flex items-center justify-between gap-3"><strong className="text-sm">Build a real-time task app</strong><span className="rounded bg-violet-300/10 px-2 py-1 font-mono text-[9px] text-violet-200">LEVEL 04</span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[68%] rounded-full bg-gradient-to-r from-violet-400 to-cyan-300" /></div><div className="mt-2 flex justify-between font-mono text-[10px] text-white/45"><span>7 of 10 missions</span><span>68%</span></div></div><div className="mt-3 grid grid-cols-2 gap-3"><MiniStat label="Current streak" value="12 days" /><MiniStat label="Rank points" value="1,280 ↑" /></div><div className="mt-5 flex h-16 items-end gap-2">{[32, 43, 36, 55, 48, 72, 95].map((height, index) => <span key={index} style={{ height: `${height}%` }} className={`flex-1 rounded-t ${index === 6 ? "bg-cyan-300" : "bg-violet-300/30"}`} />)}</div></div><div className="absolute -right-4 top-10 rounded-2xl border border-white/15 bg-[#1a1b33]/90 px-4 py-3 shadow-xl backdrop-blur"><span className="text-amber-200"><Crown className="mr-1 inline size-4" /></span><b className="text-sm">#06</b><small className="mt-1 block font-mono text-[10px] text-white/45">in your circle</small></div><div className="absolute -bottom-4 -left-4 rounded-2xl border border-white/15 bg-[#1a1b33]/90 px-4 py-3 shadow-xl backdrop-blur"><GitCommitHorizontal className="mr-1 inline size-4 text-cyan-200" /><b className="text-sm text-cyan-100">+ 1 commit</b><small className="mt-1 block font-mono text-[10px] text-white/45">streak protected</small></div></motion.div>; }
function MiniStat({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-white/[.06] p-3"><span className="block text-[10px] text-white/45">{label}</span><b className="mt-1 block font-mono text-sm">{value}</b></div>; }
function SectionHeading({ kicker, title, text }: { kicker: string; title: string; text: string }) { return <motion.div initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .55 }} className="mx-auto mb-12 max-w-xl text-center"><p className="font-mono text-[11px] tracking-[.1em] text-cyan-200">{kicker.toUpperCase()}</p><h2 className="mt-3 text-4xl font-bold leading-[1.05] tracking-[-.055em] sm:text-5xl">{title}</h2><p className="mt-4 text-sm leading-6 text-white/55">{text}</p></motion.div>; }
